# Javascript Node CircleCI 2.0 configuration file
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.0
  aws-s3: circleci/aws-s3@4.0.0
  email: cinotify/email@1.2.1

parameters:
  testBucketUri: 
    type: string
    default: s3://devops-circleci-app-test-us-east-1-007756798683/
  prodBucketUri: 
    type: string
    default: s3://devops-circleci-app-prod-us-east-1-007756798683/

jobs:

  build:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build

  deploy-test:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION_NAME}
      - aws-s3/sync:
          from: build/
          to: << parameters.testBucketUri >>

  deploy-production:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION_NAME}
      - aws-s3/sync:
          from: build/
          to: << parameters.prodBucketUri >>
  
  send_email:
    executor: email/default
    steps:
      - run: echo ${EMAIL_ID}
      - email/send:
          body: "Congratulations! The CircleCI pipeline for your project has completed successfully."
          subject: "CircleCI Pipeline Completed"
          to: ${EMAIL_ID}

workflows:
  version: 2.1
  build-deploy-and-notify:
    jobs:
      - build
      - deploy-test:
          context: aws_access_variables
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - hold:
          type: approval
          requires:
            - deploy-test
      - deploy-production:
          context: aws_access_variables
          requires:
            - deploy-test
            - hold
          filters:
            branches:
              only:
                - main
      - send_email:
          context: circleci_variables
          requires:
            - deploy-production
            - hold