# Javascript Node CircleCI 2.0 configuration file
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0.0
  # email: circleci/email@1.2.3 #cinotify/email@1.2.1
  # mailer-orb: sudiptog81/mailer-orb@1.0.0

working_directory: ~/static_website_deployment
jobs:

  build:
    docker:
      - image: cimg/node:20.6.0 #circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./static_website_deployment
          paths:
            - package.json
            - node_modules
            - src
            - build
            
  deploy-production:
    docker:
      - image: cimg/aws:2023.08 #docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./static_website_deployment
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY
          aws_secret_access_key: AWS_ACCESS_SECRET	
          region: AWS_REGION_NAME
      - aws-s3/sync:
          from: ./static_website_deployment/build/
          to: 's3://devops-circleci-prod-app-dev-us-east-1-007756798683/'
  
  # send-email:
  #   executor: email/default
  #   steps:
  #     - email/notify:
  #         to:
  #           - uzair.mansoor@netsoltech.com
  #         subject: "CircleCI Pipeline Completed"
  #         body: "Congratulations! The CircleCI pipeline for your project has completed successfully."

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      # - send-email:
      #     requires:
      #       - deploy-production

      # - mailer-orb/mail:
      #     body: Congratulations! Your circleci pipeline completed successfully.
      #     subject: CirclecI build-and-deploy job completed
      #     to: uzair.mansoor@netsoltech.com
      #     requires:
      #       - deploy-production

      # - email/send:
      #     body: Congratulations! Your circleci pipeline completed successfully.
      #     subject: CirclecI build-and-deploy job completed
      #     to: uzair.mansoor@netsoltech.com
      #     requires:
      #       - deploy-production
