# Javascript Node CircleCI 2.0 configuration file
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0.0
  email: cinotify/email@1.2.1
  node: circleci/node@5.1.0

# working_directory: ~/static_website_deployment
jobs:

  # build:
  #   docker:
  #     - image: cimg/node:20.6.0 #circleci/node:8.9.1
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install dependencies
  #         command: npm install
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #         paths:
  #           - node_modules
  #     - run:
  #         name: Build the application
  #         command: npm run build
  #     - persist_to_workspace:
  #         root: ./
  #         paths:
  #           - package.json
  #           - node_modules
  #           - src
  #           - build

  build:
    executor: node/default
    steps:
      - run: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build
            
  # deploy-production:
  #   # docker:
  #   #   - image: cimg/aws:2023.08 #docker:17.05.0-ce-git
  #   executor: aws-cli/default
  #   steps:
  #     - attach_workspace:
  #         at: ./
  #     - run: echo ${AWS_ACCESS_KEY_ID} >> AWS_ACCESS_KEY_ID
  #     - run: echo ${AWS_ACCESS_KEY_ID}
  #     - run: echo ${AWS_SECRET_ACCESS_KEY} >> AWS_SECRET_ACCESS_KEY
  #     - run: echo ${AWS_REGION_NAME} >> AWS_REGION_NAME
  #     - aws-cli/setup:
  #         aws_access_key_id: AWS_ACCESS_KEY_ID
  #         aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  #         region: AWS_REGION_NAME
  #     # - run: aws s3 sync build/ s3://devops-circleci-prod-app-dev-us-east-1-007756798683/
  #     - aws-s3/sync:
  #         from: build/
  #         to: 's3://devops-circleci-prod-app-dev-us-east-1-007756798683/'
  
  deploy-production:
    docker:
      - image: cimg/aws:2023.08 #docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./
      - run: aws s3 sync build/ s3://devops-circleci-prod-app-dev-us-east-1-007756798683/
  
  send-email:
    executor: email/default
    steps:
      - run: echo ${email_id} >> email_id
      - email/send:
          to: context:circleci_variables.email_id
          subject: "CircleCI Pipeline Completed"
          body: "Congratulations! The CircleCI pipeline for your project has completed successfully."

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy-production:
          context: circleci_variables
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - send-email:
          context: circleci_variables
          requires:
            - deploy-production