# Javascript Node CircleCI 2.0 configuration file
version: 2

orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build:
    docker:
      - image: cimg/node:20.6.0 #circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
          output-format: OUTPUT_FORMAT

  deploy-test:
    docker:
      - image: cimg/aws:2023.08 #docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            aws s3 sync build/ s3://devops-circleci-test-app-dev-us-east-1-007756798683
            
  deploy-production:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            aws configure
            aws s3 sync build/ s3://devops-circleci-prod-app-dev-us-east-1-007756798683

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
  build-test-and-deploy:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only:
                - test
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - main